---
- hosts: localhost
  gather_facts: yes


- hosts: "{{ target_host }}"
  gather_facts: no
  roles:
    - role: vagrant
      vagrant_task: halt
      vagrant_host: "{{ host_alias | default(inventory_hostname) }}"
      vagrant_root_path: "{{ inventory_dir | dirname }}/vagrant"
      delegate_to: localhost
      when: playbook_is_vagrant_host
